# .github/workflows/build-and-analyze.yml

name: Build, Analyze and Test

on:
  # Corrigido para a branch 'main'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read # Permite que o SonarCloud decore os PRs com resultados da análise
  
jobs:
  build-and-analyze:
    name: Build, Analyze and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Build, Test and Analyze with SonarCloud
        # Este único comando faz tudo: compila, testa e envia a análise para o SonarCloud
        # As propriedades -Dsonar... são passadas diretamente para o plugin do Sonar no Maven
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
          -Dsonar.projectKey=pedroluizmossi_caching-x-lib 
          -Dsonar.organization=pedroluizmossi
        env:
          # Token do GitHub é necessário para o Sonar decorar a Pull Request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Token do SonarCloud para autenticação
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
